# Generated by Django 4.2 on 2023-04-21 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('artists', models.ManyToManyField(to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PodcastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('likes_count', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('media', models.CharField(max_length=200)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_media', to='podcast.podcast')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('podcast', 'title')},
            },
        ),
        migrations.CreateModel(
            name='PodcastProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paused_at', models.PositiveIntegerField(default=0)),
                ('last_played', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podcast.podcastmedia')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='podcast',
            name='categories',
            field=models.ManyToManyField(blank=True, to='podcast.podcastcategory'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Favourite', max_length=250)),
                ('podcast_medias', models.ManyToManyField(blank=True, to='podcast.podcastmedia')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='users.profile')),
            ],
            options={
                'unique_together': {('profile', 'name')},
            },
        ),
    ]
