# Generated by Django 4.2 on 2023-04-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastprogress',
            name='paused_at',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
