# Generated by Django 4.2 on 2023-04-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_alter_podcast_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastmedia',
            name='media',
            field=models.FileField(null=True, upload_to='podcast_media/'),
        ),
    ]
