# Generated by Django 4.2 on 2023-04-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_alter_podcastmedia_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastmedia',
            name='duration',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
